# Generated by Django 6.0.1 on 2026-02-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_browser_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('permissions', models.JSONField(default=dict, verbose_name='الصلاحيات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دور مخصص',
                'verbose_name_plural': 'الأدوار المخصصة',
            },
        ),
    ]
