# Generated by Django 6.0.1 on 2026-02-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم الدور'),
        ),
    ]
