# Generated by Django 6.0.1 on 2026-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemsettings_assign_tags_to_entries_and_more'),
        ('users', '0004_alter_customrole_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_branches',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='core.branch', verbose_name='الفروع المسموحة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='manage_all_branches',
            field=models.BooleanField(default=False, verbose_name='إدارة جميع الفروع'),
        ),
    ]
