# Generated by Django 6.0.1 on 2026-01-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0007_systemsettings_show_driver_in_permit_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='accounting.account', verbose_name='حساب الأستاذ'),
        ),
        migrations.AddField(
            model_name='safe',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safe', to='accounting.account', verbose_name='حساب الأستاذ'),
        ),
    ]
