# Generated by Django 6.0.1 on 2026-01-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalitem_vat_amount_journalitem_vat_rate_and_more'),
        ('core', '0008_contact_account_safe_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='store', to='accounting.account', verbose_name='حساب المخزون'),
        ),
    ]
