# Generated by Django 6.0.1 on 2026-01-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0009_store_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_cogs', to='accounting.account', verbose_name='حساب تكلفة البضاعة المباعة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='purchases_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchases', to='accounting.account', verbose_name='حساب المشتريات الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_sales', to='accounting.account', verbose_name='حساب المبيعات الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vat_input_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vat_in', to='accounting.account', verbose_name='حساب ضريبة المدخلات (المشتريات)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vat_output_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_vat_out', to='accounting.account', verbose_name='حساب ضريبة المخرجات (المبيعات)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة (%)'),
        ),
    ]
