# Generated by Django 6.0.1 on 2026-01-29 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0010_systemsettings_cogs_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_expense', to='accounting.account', verbose_name='حساب المصروفات الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_income', to='accounting.account', verbose_name='حساب الإيرادات الافتراضي'),
        ),
    ]
