# Generated by Django 6.0.1 on 2026-01-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0011_systemsettings_default_expense_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_loans_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_loans', to='accounting.account', verbose_name='حساب سلف الموظفين'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_salaries_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_salaries', to='accounting.account', verbose_name='حساب الرواتب والأجور'),
        ),
    ]
