# Generated by Django 6.0.1 on 2026-01-31 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_systemsettings_default_loans_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='initial_balance_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='contact',
            name='initial_balance_type',
            field=models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], default='debit', max_length=10, verbose_name='نوع الرصيد الافتتاحي'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pricing_system',
            field=models.CharField(choices=[('retail', 'مستهلك'), ('wholesale', 'جملة'), ('distributor', 'مورد'), ('supplier', 'سعر المورد')], default='retail', max_length=20, verbose_name='نظام التسعير'),
        ),
    ]
