# Generated by Django 6.0.1 on 2026-02-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_contact_initial_balance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enable_notifications',
            field=models.BooleanField(default=True, verbose_name='تفعيل التنبيهات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='system_language',
            field=models.CharField(default='ar', max_length=10, verbose_name='لغة النظام'),
        ),
    ]
