# Generated by Django 6.0.1 on 2026-02-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_depreciation_method',
            field=models.CharField(choices=[('straight_line', 'القسط الثابت'), ('reducing_balance', 'القسط المتناقص')], default='straight_line', max_length=20, verbose_name='طريقة الإهلاك الافتراضية'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='fiscal_year_start',
            field=models.DateField(blank=True, null=True, verbose_name='بداية السنة المالية'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='lock_date',
            field=models.DateField(blank=True, help_text='لا يمكن إضافة أو تعديل قيود قبل هذا التاريخ', null=True, verbose_name='تاريخ إغلاق العمليات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_journal_approval',
            field=models.BooleanField(default=False, verbose_name='طلب الموافقة على القيود اليدوية'),
        ),
    ]
