# Generated by Django 6.0.1 on 2026-02-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_systemsettings_default_depreciation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='link_cost_centers',
            field=models.BooleanField(default=True, verbose_name='ربط مراكز التكلفة بين الفروع'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='main_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='is_main_for', to='core.branch', verbose_name='الفرع الرئيسي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='per_branch_accounts',
            field=models.BooleanField(default=False, verbose_name='تخصيص الحسابات على مستوى الفروع'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='share_customers',
            field=models.BooleanField(default=False, verbose_name='مشاركة العملاء بين الفروع'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='share_products',
            field=models.BooleanField(default=False, verbose_name='مشاركة المنتجات بين الفروع'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='share_suppliers',
            field=models.BooleanField(default=False, verbose_name='مشاركة الموردين بين الفروع'),
        ),
    ]
