# Generated by Django 6.0.1 on 2026-02-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0017_systemsettings_link_cost_centers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_adjustment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_adjustment', to='accounting.account', verbose_name='حساب تسوية المبيعات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_bank_default', to='accounting.account', verbose_name='حساب البنوك العام'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_customer_default', to='accounting.account', verbose_name='حساب العملاء الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_discount_allowed', to='accounting.account', verbose_name='حساب الخصم المسموح به'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_discount_earned_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_discount_earned', to='accounting.account', verbose_name='حساب الخصم المكتسب'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_purchase_adjustment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchase_adjustment', to='accounting.account', verbose_name='حساب تسوية المشتريات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_safe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_safe_default', to='accounting.account', verbose_name='حساب الخزائن العام'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_supplier_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_supplier_default', to='accounting.account', verbose_name='حساب الموردين الافتراضي'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_warehouse_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_warehouse_default', to='accounting.account', verbose_name='حساب المستودعات العام'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_inventory', to='accounting.account', verbose_name='حساب المخزون العام'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='product_sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_product_sales', to='accounting.account', verbose_name='حساب مبيعات المنتجات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='purchase_returns_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_purchase_returns', to='accounting.account', verbose_name='حساب مرتجعات المشتريات'),
        ),
    ]
