# Generated by Django 6.0.1 on 2026-02-07 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0018_systemsettings_default_adjustment_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sales_return_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_sales_return', to='accounting.account', verbose_name='حساب مرتجعات المبيعات'),
        ),
    ]
