# Generated by Django 6.0.1 on 2026-02-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_systemsettings_sales_return_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='assign_tags_to_entries',
            field=models.BooleanField(default=False, verbose_name='تعيين وسوم إلى حركات القيود'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='distribute_cost_center_per_item_in_inventory_permits',
            field=models.BooleanField(default=False, verbose_name='توزيع مراكز التكلفة في الأذون المخزنية حسب البند'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='distribute_cost_center_per_item_in_invoices',
            field=models.BooleanField(default=False, verbose_name='توزيع مراكز التكلفة في الفواتير حسب البند'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='distribute_cost_center_per_item_in_purchases',
            field=models.BooleanField(default=False, verbose_name='توزيع مراكز التكلفة في فواتير الشراء حسب البند'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='per_item_account_in_inventory_permits',
            field=models.BooleanField(default=False, verbose_name='تحديد حساب لكل بند في الأذون المخزنية'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='per_item_account_in_invoices',
            field=models.BooleanField(default=False, verbose_name='تحديد حساب لكل بند في الفواتير'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='per_item_account_in_purchases',
            field=models.BooleanField(default=False, verbose_name='تحديد حساب لكل بند في المشتريات'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_cost_center_in_journal',
            field=models.BooleanField(default=False, verbose_name='عرض مركز التكلفة في القيود اليومية'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='show_tax_in_journal',
            field=models.BooleanField(default=True, verbose_name='عرض الضريبة في القيود اليومية'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='update_currency_rates_automatically',
            field=models.BooleanField(default=False, verbose_name='تحديث أسعار العملات تلقائياً'),
        ),
    ]
