# Generated by Django 6.0.1 on 2026-02-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0020_systemsettings_assign_tags_to_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='current_supplier_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي (مورد)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_as_customer', to='accounting.account', verbose_name='حساب العميل'),
        ),
        migrations.AddField(
            model_name='contact',
            name='initial_supplier_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الافتتاحي للمورد'),
        ),
        migrations.AddField(
            model_name='contact',
            name='initial_supplier_balance_type',
            field=models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], default='credit', max_length=10, verbose_name='نوع الرصيد الافتتاحي للمورد'),
        ),
        migrations.AddField(
            model_name='contact',
            name='supplier_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact_as_supplier', to='accounting.account', verbose_name='حساب المورد'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='accounting.account', verbose_name='حساب الأستاذ (قديم)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('supplier', 'مورد'), ('both', 'عميل ومورد')], max_length=20, verbose_name='نوع جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي (عميل)'),
        ),
    ]
