# Generated by Django 6.0.1 on 2026-02-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_current_supplier_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='default_customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'contact_type__in': ['customer', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_customer_settings', to='core.contact', verbose_name='العميل الافتراضي لفواتير البيع'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_supplier',
            field=models.ForeignKey(blank=True, limit_choices_to={'contact_type__in': ['supplier', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_supplier_settings', to='core.contact', verbose_name='المورد الافتراضي لفواتير الشراء'),
        ),
    ]
