# Generated by Django 6.0.1 on 2026-02-09 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('core', '0022_alter_systemsettings_default_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='damaged_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_damaged', to='accounting.account', verbose_name='حساب التالف'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='duplicate_item_handling',
            field=models.CharField(choices=[('allow_duplicate', 'السماح بتكرار الصنف في بنود الفاتورة'), ('increase_quantity', 'زيادة الكمية تلقائياً عند تكرار الصنف'), ('prevent_duplicate', 'منع تكرار الصنف في الفاتورة')], default='increase_quantity', max_length=20, verbose_name='التعامل مع تكرار الصنف'),
        ),
    ]
