# Generated by Django 6.0.1 on 2026-02-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_date_alter_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
    ]
