# Generated by Django 6.0.1 on 2026-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoiceitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount_type',
            field=models.CharField(choices=[('value', 'قيمة'), ('percent', 'نسبة')], default='value', max_length=10, verbose_name='نوع الخصم'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة/نسبة الخصم'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_type',
            field=models.CharField(choices=[('value', 'قيمة'), ('percent', 'نسبة')], default='value', max_length=10, verbose_name='نوع الضريبة'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة/نسبة الضريبة'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الخصم النهائي'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الضريبة النهائي'),
        ),
    ]
