# Generated by Django 6.0.1 on 2026-02-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemsettings_assign_tags_to_entries_and_more'),
        ('finances', '0021_alter_openingbalance_number'),
        ('invoices', '0007_invoice_discount_type_invoice_discount_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_payments', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='payment',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finances.expensecategory', verbose_name='قسم المصروفات'),
        ),
        migrations.AddField(
            model_name='payment',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finances.incomecategory', verbose_name='قسم الإيرادات'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_payments', to='core.safe', verbose_name='الخزنة'),
        ),
    ]
