# Generated by Django 6.0.1 on 2026-02-07 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('invoices', '0008_payment_bank_payment_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_payment', to='accounting.journalentry', verbose_name='القيد المحاسبي المنشأ'),
        ),
    ]
