# Generated by Django 6.0.1 on 2026-02-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_current_supplier_balance_and_more'),
        ('invoices', '0009_payment_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.contact', verbose_name='جهة الاتصال'),
        ),
    ]
