# Generated by Django 6.0.1 on 2026-02-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('invoices', '0010_alter_invoice_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='accounting.account', verbose_name='الحساب المحاسبي'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
    ]
