# Generated by Django 6.0.1 on 2026-02-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoiceitem_account_invoiceitem_cost_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء'), ('sale_return', 'مرتجع بيع'), ('purchase_return', 'مرتجع شراء'), ('damaged', 'تالف')], max_length=20, verbose_name='نوع الفاتورة'),
        ),
    ]
