# Generated by Django 6.0.1 on 2026-02-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_systemsettings_damaged_account_and_more'),
        ('invoices', '0012_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.contact', verbose_name='جهة الاتصال'),
        ),
    ]
