# Generated by Django 6.0.1 on 2026-02-12 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_systemsettings_damaged_account_and_more'),
        ('invoices', '0013_alter_invoice_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.contact', verbose_name='العميل/المورد'),
        ),
    ]
