# Generated by Django 6.0.1 on 2026-01-29 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('finances', '0014_alter_storepermit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_category', to='accounting.account', verbose_name='حساب الأستاذ'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_category', to='accounting.account', verbose_name='حساب الأستاذ'),
        ),
    ]
