# Generated by Django 6.0.1 on 2026-02-06 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_financialperiod_options_fixedasset'),
        ('finances', '0015_expensecategory_account_incomecategory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الضريبة'),
        ),
        migrations.AddField(
            model_name='income',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='accounting.costcenter', verbose_name='مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='income',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الضريبة'),
        ),
    ]
