# Generated by Django 6.0.1 on 2026-02-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank'),
        ('finances', '0016_expense_cost_center_expense_vat_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='safetransaction',
            options={'ordering': ['date'], 'verbose_name': 'حركة مالية', 'verbose_name_plural': 'حركات مالية'},
        ),
        migrations.AddField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='safedeposit',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='safetransaction',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AddField(
            model_name='safewithdrawal',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.bank', verbose_name='البنك'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='core.safe', verbose_name='الخزنة'),
        ),
        migrations.AlterField(
            model_name='income',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='core.safe', verbose_name='الخزنة'),
        ),
        migrations.AlterField(
            model_name='safedeposit',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='core.safe', verbose_name='الخزنة'),
        ),
        migrations.AlterField(
            model_name='safetransaction',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.safe', verbose_name='الخزنة'),
        ),
        migrations.AlterField(
            model_name='safewithdrawal',
            name='safe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='core.safe', verbose_name='الخزنة'),
        ),
    ]
