# Generated by Django 6.0.1 on 2026-02-06 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank'),
        ('finances', '0017_alter_safetransaction_options_expense_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='رقم المستند')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ المستند')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم المرجعي')),
                ('is_posted', models.BooleanField(default=True, verbose_name='مرحل')),
                ('deposit_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_in', to='finances.safetransaction', verbose_name='حركة الإيداع المنشأة')),
                ('from_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.bank', verbose_name='من بنك')),
                ('from_safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.safe', verbose_name='من خزنة')),
                ('to_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.bank', verbose_name='إلى بنك')),
                ('to_safe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.safe', verbose_name='إلى خزنة')),
                ('withdrawal_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_out', to='finances.safetransaction', verbose_name='حركة السحب المنشأة')),
            ],
            options={
                'verbose_name': 'تحويل أموال',
                'verbose_name_plural': 'تحويلات الأموال',
            },
        ),
    ]
