# Generated by Django 6.0.1 on 2026-02-06 17:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_bank'),
        ('finances', '0018_moneytransfer'),
        ('products', '0003_product_tax_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='رقم التسوية')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسوية')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('adjustment_type', models.CharField(choices=[('increase', 'زيادة'), ('decrease', 'نقصان')], max_length=10, verbose_name='نوع التسوية')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب التسوية')),
                ('is_posted', models.BooleanField(default=True, verbose_name='مرحل')),
                ('created_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_record', to='finances.producttransaction')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='products.product', verbose_name='المنتج')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit', verbose_name='الوحدة')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='core.store', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='رقم التحويل')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحويل')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=True, verbose_name='مرحل')),
                ('deposit_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_in', to='finances.producttransaction')),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='core.store', verbose_name='من مخزن')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transfers', to='products.product', verbose_name='المنتج')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit', verbose_name='الوحدة')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='core.store', verbose_name='إلى مخزن')),
                ('withdrawal_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_out', to='finances.producttransaction')),
            ],
            options={
                'verbose_name': 'تحويل مخزني',
                'verbose_name_plural': 'تحويلات مخزنية',
            },
        ),
    ]
