# Generated by Django 6.0.1 on 2026-02-07 10:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemsettings_assign_tags_to_entries_and_more'),
        ('finances', '0019_inventoryadjustment_stocktransfer'),
        ('products', '0003_product_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'بيع'), ('purchase', 'شراء'), ('sale_return', 'مرتجع بيع'), ('purchase_return', 'مرتجع شراء'), ('adjustment', 'تسوية مخزون'), ('opening_balance', 'رصيد أول المدة')], max_length=20, verbose_name='نوع العملية'),
        ),
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='رقم المستند')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_posted', models.BooleanField(default=False, verbose_name='مرحل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_balances', to='core.store', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'رصيد أول المدة',
                'verbose_name_plural': 'أرصدة أول المدة',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='السعر')),
                ('update_purchase_price', models.BooleanField(default=False, verbose_name='تحديث سعر الشراء')),
                ('created_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_item', to='finances.producttransaction')),
                ('opening_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.openingbalance', verbose_name='مستند رصيد أول المدة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='المنتج')),
                ('product_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'بند رصيد أول المدة',
                'verbose_name_plural': 'بنود رصيد أول المدة',
            },
        ),
    ]
