# Generated by Django 6.0.1 on 2026-02-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_alter_producttransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openingbalance',
            name='number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم المستند'),
        ),
    ]
