# Generated by Django 6.0.1 on 2026-02-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contact_current_supplier_balance_and_more'),
        ('finances', '0021_alter_openingbalance_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.contact', verbose_name='جهة الاتصال المرتبطة'),
        ),
        migrations.AddField(
            model_name='expense',
            name='contact_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense', to='finances.contacttransaction', verbose_name='حركة حساب جهة الاتصال'),
        ),
        migrations.AddField(
            model_name='income',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incomes', to='core.contact', verbose_name='جهة الاتصال المرتبطة'),
        ),
        migrations.AddField(
            model_name='income',
            name='contact_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income', to='finances.contacttransaction', verbose_name='حركة حساب جهة الاتصال'),
        ),
        migrations.AlterField(
            model_name='contacttransaction',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.contact', verbose_name='جهة الاتصال'),
        ),
    ]
