# Generated by Django 6.0.1 on 2026-01-29 16:32

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('is_closed', models.BooleanField(default=False, verbose_name='مغلقة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الفترة')),
            ],
            options={
                'verbose_name': 'فترة مالية',
                'verbose_name_plural': 'الفترات المالية',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=50, unique=True, verbose_name='رقم القيد')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('description', models.TextField(blank=True, verbose_name='الوصف/البيان')),
                ('reference', models.CharField(blank=True, help_text='رقم الفاتورة أو رقم السند المرتبط', max_length=100, verbose_name='المرجع')),
                ('is_posted', models.BooleanField(default=False, verbose_name='تم الترحيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قيد محاسبي',
                'verbose_name_plural': 'القيود المحاسبية',
                'ordering': ['-date', '-entry_number'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحساب')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الحساب')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('income', 'إيرادات'), ('expense', 'مصروفات')], max_length=20, verbose_name='نوع الحساب')),
                ('is_selectable', models.BooleanField(default=True, help_text='إذا كان خطأ، فهذا حساب أب للتجميع فقط', verbose_name='قابل للتحديد في القيود')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='الرصيد الحالي')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='الحساب الأب')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'شجرة الحسابات',
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='دائن')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة السطر')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_items', to='accounting.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry', verbose_name='القيد')),
            ],
            options={
                'verbose_name': 'سطر قيد',
                'verbose_name_plural': 'سطور القيود',
            },
        ),
    ]
