# Generated by Django 6.0.1 on 2026-01-29 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_costcenter_journalitem_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ الضريبة'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الضريبة (%)'),
        ),
        migrations.AlterField(
            model_name='journalitem',
            name='memo',
            field=models.CharField(blank=True, max_length=255, verbose_name='بيان'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'إنشاء'), ('UPDATE', 'تعديل'), ('DELETE', 'حذف'), ('POST', 'ترحيل'), ('UNPOST', 'إلغاء ترحيل')], max_length=10, verbose_name='الإجراء')),
                ('model_name', models.CharField(max_length=50, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(verbose_name='رقم الكائن')),
                ('object_repr', models.CharField(max_length=200, verbose_name='وصف الكائن')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='التغييرات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجل التدقيق',
                'ordering': ['-timestamp'],
            },
        ),
    ]
