# Generated by Django 6.0.1 on 2026-01-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalitem_vat_amount_journalitem_vat_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialperiod',
            options={'ordering': ['-start_date'], 'verbose_name': 'فترة مالية', 'verbose_name_plural': 'الفترات المالية'},
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الأصل')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الأصل')),
                ('acquisition_date', models.DateField(verbose_name='تاريخ الاستحواذ')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='تكلفة الاستحواذ')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='قيمة الخردة')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='العمر الإنتاجي (سنوات)')),
                ('depreciation_method', models.CharField(choices=[('SL', 'القسط الثابت - Straight Line'), ('DB', 'الرصيد المتناقص - Declining Balance')], default='SL', max_length=2, verbose_name='طريقة الإهلاك')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='القيمة الدفترية الحالية')),
                ('last_depreciation_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر إهلاك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account', verbose_name='حساب الأصل')),
                ('depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciated_assets', to='accounting.account', verbose_name='حساب مجمع الإهلاك')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expenses', to='accounting.account', verbose_name='حساب مصروف الإهلاك')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
            },
        ),
    ]
