# Generated by Django 6.0.1 on 2026-01-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalitem_vat_amount_journalitem_vat_rate_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_cogs', to='accounting.account', verbose_name='حساب تكلفة المبيعات'),
        ),
        migrations.AddField(
            model_name='category',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_inventories', to='accounting.account', verbose_name='حساب المخزون'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم القسم'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='القسم الرئيسي'),
        ),
    ]
