# Generated by Django 6.0.1 on 2026-02-09 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_tax_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('simple', 'منتج بسيط'), ('service', 'خدمة'), ('assembly', 'منتج تجميعي')], default='simple', max_length=20, verbose_name='طبيعة المنتج'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_type',
            field=models.CharField(choices=[('percentage', 'نسبة'), ('value', 'قيمة')], default='percentage', max_length=20, verbose_name='نوع الضريبة'),
        ),
        migrations.AddField(
            model_name='product',
            name='tax_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='قيمة/نسبة الضريبة'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'نسبة'), ('value', 'قيمة')], default='percentage', max_length=20, verbose_name='نوع الخصم'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='purchase_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الشراء'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='selling_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم المستهلك'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_tax_type',
            field=models.CharField(blank=True, choices=[('percentage', 'نسبة'), ('value', 'قيمة')], max_length=20, null=True, verbose_name='نوع ضريبة الوحدة'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='unit_tax_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قيمة ضريبة الوحدة'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='wholesale_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الجملة'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سعر الجملة'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='سعر البيع (مستهلك)'),
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='الكمية')),
                ('assembly_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='products.product', verbose_name='المنتج التجميعي')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_assemblies', to='products.product', verbose_name='المكون')),
            ],
            options={
                'verbose_name': 'مكون المنتج',
                'verbose_name_plural': 'مكونات المنتج التجميعي',
                'unique_together': {('assembly_product', 'component_product')},
            },
        ),
    ]
