# Generated by Django 6.0.1 on 2026-02-09 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_tax_rate_product_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'حقل مخصص',
                'verbose_name_plural': 'الحقول المخصصة',
            },
        ),
        migrations.CreateModel(
            name='ProductCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='القيمة')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productcustomfield', verbose_name='الحقل المخصص')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='products.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'قيمة حقل مخصص',
                'verbose_name_plural': 'قيم الحقول المخصصة',
                'unique_together': {('product', 'custom_field')},
            },
        ),
    ]
